- ignore: { name: Avoid lambda }
- ignore: { name: Eta reduce }
- ignore: { name: Reduce duplication }
- ignore: { name: Redundant do }
- ignore: { name: Use first }
- ignore: { name: Use list comprehension }
- ignore: { name: Use record patterns }
- ignore: { name: Use uncurry }
