name:                Jikka
version:             5.0.5.0
github:              "kmyk/Jikka"
license:             Apache
author:              "Kimiyuki Onaka"
maintainer:          "kimiyuk95@gmail.com"
copyright:           "2021 Kimiyuki Onaka"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kmyk/Jikka>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- array
- deepseq
- mtl
- vector
- transformers

library:
  source-dirs: src

  build-tools:
  - alex
  - happy

  ghc-options:
  - -W
  - -Werror
  - -optP-Wno-nonportable-include-path

executables:
  jikka:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -W
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optP-Wno-nonportable-include-path
    dependencies:
    - Jikka

tests:
  jikka-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -W
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optP-Wno-nonportable-include-path
    dependencies:
    - Jikka
    - ormolu
    - hlint
    - hspec
    build-tools:
    - hspec-discover

  jikka-doctest:
    main:                doctests.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optP-Wno-nonportable-include-path
    dependencies:
    - Jikka
    - doctest
