name: clang-format

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run clang-format
      run: |
        set -ex; for f in $(find runtime/include examples/data -name \*.\?pp); do diff $f <(clang-format $f); done
