name: docs

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Haskell
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true

      - uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}

      - name: Build dependencies
        run: stack --system-ghc build --only-dependencies

      - name: Run Haddock
        run: stack --system-ghc haddock --haddock-arguments --odir=docs/gh-pages/haddock

      - name: Make Gallery
        run: |
          python3 scripts/make_gallery.py > docs/gh-pages/gallery/data.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/gh-pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
