name: format-yaml

on: [push, pull_request]

jobs:
  format-yaml:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Run Prettier
        run: |
          yarn prettier --check $(git ls-files | grep '\.yml$\|\.yaml$\|\.json$')
        shell: bash
