name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Haskell
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true

    - uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-test-${{ hashFiles('stack.yaml') }}

    - name: Build dependencies
      run: stack --system-ghc build --test --only-dependencies

    - name: Build
      run: stack --system-ghc build --ghc-options=-Werror

    - name: Run unit tests
      run: stack --system-ghc test --ghc-options=-Werror

    - name: Run integration tests
      run: bash examples/test.sh
