name: upload-binaries

on:
  release:
    types: [published]

jobs:
  upload-binaries:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Haskell
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true

    - uses: actions/cache@v2
      with:
        path: |
          ~/.stack
          ${{ env.STACK_ROOT }}
        key: ${{ runner.os }}-stack-test-${{ hashFiles('stack.yaml') }}

    - name: Build dependencies
      run: stack --system-ghc build --test --only-dependencies

    - name: Build
      run: stack --system-ghc build --ghc-options=-Werror

    - name: Set extension to .exe on Windows
      run: echo "::set-env name=EXT::.exe"
      if: matrix.os == 'windows-latest'

    - name: Get binary path
      run: |
        echo "::set-env name=BINARY_PATH::$(stack --system-ghc path --local-install-root)/bin/jikka${{ env.EXT }}"
      shell: bash

    - name: Compress binary
      uses: svenstaro/upx-action@2.0.1
      with:
        file: ${{ env.BINARY_PATH }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.BINARY_PATH }}
        asset_name: jikka-${{ github.event.release.tag_name }}-${{ runner.os }}${{ env.EXT }}
        asset_content_type: application/octet-stream
